import { Geist, Geist_Mono, Metal_Mania, Audiowide } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./ReduxProvider/ReduxProvider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const metalMania = Metal_Mania({
  variable: "--font-metal-mania",
  subsets: ["latin"],
  weight: ["400"],
});

const audioWide = Audiowide({
  variable: "--font-audiowide",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Indolanka-Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${metalMania.variable} ${audioWide.variable} antialiased`}
      >
        <ReduxProvider>
          {children}
          <Toaster
            toastOptions={{
              className: "rounded-2xl border shadow-lg",
              style: {
                //background: "#1e1e1e",
                // color: "#fff",
                fontSize: "16px",
                //color: "white",
                borderLeft: "10px solid ",
              },
            }}
          />
        </ReduxProvider>
      </body>
    </html>
  );
}
